<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quotes.Model\Quotes.Model.csproj" />
    <ProjectReference Include="..\Quotes.Repository\Quotes.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Quotes.Model.Shared" />
    <Using Include="Quotes.Model.Quotes" />
    <Using Include="Quotes.Repository.Entities" />
    <Using Include="Quotes.Repository.Context" />
    <Using Include="Quotes.Business.Services" />
    <Using Include="Quotes.Business.Observability" />
  </ItemGroup>

</Project>
